services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "fullstack@123"
    ports:
      - "1434:1434"
    volumes:
      - "sqlserver:/var/opt/mssql"
    
  client-app:
    image: angular-test
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  webapi:
  sqlserver: 
  client-app: